package org.example.server.config;

import org.example.api.ClashApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class ClashApiConfig {

    @Bean
    public ClashApi clashApi() {
        return new ClashApi("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY0MTFkMmY0LTQ3MDAtNGY5Mi05ODIxLTYzYTc5MjBjYmM5NCIsImlhdCI6MTY2Nzk3NjczMCwic3ViIjoiZGV2ZWxvcGVyL2U5YWUxNzQwLThiNjgtYzAzZS04ZjIzLTkzODAwNWU0YzA5OSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3MS4yMTcuMTMxLjExMiIsIjE3MS4yMTcuMTMxLjEyMyJdLCJ0eXBlIjoiY2xpZW50In1dfQ.RJGIUQ6Qk9lGILHg0ple9P9oOL4m-9aDbLYSOl1D3R0iTPE8fIuV_Uob9kH2Mn4f6UpCNDNHbEIaFm3Af1xO_g");
    }
}
