spring:
  application:
    name: clash-server
  data:
    mongodb:
#      uri: mongodb+srv://lck:Heikediguo123@cluster0.asnfocp.mongodb.net/?retryWrites=true&w=majority
      database: clash
      host: localhost

logging:
  level:
    org.ankol.server: debug
  file:
    path: logs
  charset:
    console: UTF-8
    file: UTF-8

clash-manager:
  clan-tag: "#280Y0YGPJ"
  api-access-token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImM1ZTlkZjBmLWM2NmMtNDI1Zi1hNmYwLTViZjFjYzkyM2ZjOSIsImlhdCI6MTcwMDAzMjM3MSwic3ViIjoiZGV2ZWxvcGVyL2U5YWUxNzQwLThiNjgtYzAzZS04ZjIzLTkzODAwNWU0YzA5OSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3MS4yMTcuMTI3LjE1MCIsIjE3MS4yMTYuODguNTYiLCIxMTkuMjM2LjE2NC4yMjAiXSwidHlwZSI6ImNsaWVudCJ9XX0.AV_EPyQpDnGcdzIYJcsAgIa4_8TjC13Gl6NLYHNw_XFcDybob2rZvvNT6kv-_uCBAHVyU8-23OQ4NHm63GlycA"